<?xml version="1.0" encoding="UTF-8"?>
<!--
  Authors: Jimmy Da Silva, Kelsey Hawkins
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

   <xacro:include filename="$(find excel_description)/urdf/kinect_frames.urdf.xacro" />

   <property name="pi" value="3.14159265" />

   <xacro:macro name="cameras" params="x_offset y_offset theta_offset">

      <link name="overhead_hum_ws_frame">
      </link>

      <joint name="overhead_hum_ws_cam_joint" type="fixed">
         <parent link="table_link" />
         <child link="overhead_hum_ws_frame" />
         <origin rpy="3.136 -0.042 ${-0.014+theta_offset}" xyz="${0.569+x_offset} ${1.521+y_offset} 2.597" />
      </joint>

      <link name="overhead_rob_ws_frame">
      </link>

      <joint name="overhead_rob_ws_cam_joint" type="fixed">
         <parent link="table_link" />
         <child link="overhead_rob_ws_frame" />
         <!--<origin rpy="3.108 -0.038 -0.005" xyz="1.625 0.149 2.643" />-->
         <origin rpy="3.108 -0.028 ${-0.025+theta_offset}" xyz="${1.624+x_offset} ${0.12+y_offset} 2.643" />
      </joint>

      <link name="kinect_front_link">
      </link>

      <joint name="kinect_front_joint" type="fixed">
         <parent link="table_link" />
         <child link="kinect_front_link" />
         <origin rpy="0.022 0.520 0.108" xyz="-1.100 1.604 2.345" />
      </joint>

      <xacro:kinect_frames camera="kinect_front"/>

      <link name="kinect_back_link">
      </link>

      <joint name="kinect_back_joint" type="fixed">
         <parent link="table_link" />
         <child link="kinect_back_link" />
         <origin rpy="0.019 0.604 -2.650" xyz="3.869 3.650 2.315" />
      </joint>

      <xacro:kinect_frames camera="kinect_back"/>

      <link name="gripper_camera_link">
      </link>

      <joint name="gripper_camera_joint" type="fixed">
         <parent link="ee_link" />
         <child link="gripper_camera_link" />
         <origin rpy="0.0 0.0 0.0" xyz="0.015 -0.02 0.06" />
      </joint>

      <link name="gripper_camera_focal_link">
      </link>

      <joint name="gripper_camera_focal_joint" type="fixed">
         <parent link="gripper_camera_link" />
         <child link="gripper_camera_focal_link" />
         <origin rpy="0.0 0.0 0.0" xyz="0.0 1.0 0.0" />
      </joint>

   </xacro:macro>
</robot>
