constraints:
  goal_time: 0.5
  stopped_velocity_tolerance: 0.02
  table_rail_joint:
    goal:       0.1
    trajectory: 0.3
  shoulder_pan_joint:
    goal:       0.1
    trajectory: 0.3
  shoulder_lift_joint:
    goal:       0.1
    trajectory: 0.3
  elbow_joint:
    goal:       0.1
    trajectory: 0.3
  wrist_1_joint:
    goal:       0.1
    trajectory: 0.3
  wrist_2_joint:
    goal:       0.1
    trajectory: 0.3
  wrist_3_joint:
    goal:       0.1
    trajectory: 0.3
