constraints:
  goal_time: 5.0
  stopped_velocity_tolerance: 0.07
  table_rail_joint:
    goal:       0.01
    trajectory: 0.1
  shoulder_pan_joint:
    goal:       0.02
    trajectory: 0.1
  shoulder_lift_joint:
    goal:       0.02
    trajectory: 0.1
  elbow_joint:
    goal:       0.02
    trajectory: 0.1
  wrist_1_joint:
    goal:       0.1
    trajectory: 0.1
  wrist_2_joint:
    goal:       0.04
    trajectory: 0.1
  wrist_3_joint:
    goal:       0.04
    trajectory: 0.1
