controller_list:
  - name: fake_excel_controller
    joints:
      - rail_base_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint