joint_limits:

  table_rail_joint:
    has_position_limits: true
    min_position: 0.4
    max_position: 3.3

    has_velocity_limits: true
    max_velocity: 0.75

    has_acceleration_limits: false
    max_acceleration: 1


  shoulder_pan_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: .7

    has_acceleration_limits: false
    max_acceleration: 3


  shoulder_lift_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: 1.0

    has_acceleration_limits: false
    max_acceleration: 5


  elbow_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: 1.0

    has_acceleration_limits: false
    max_acceleration: 5


  wrist_1_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: 1.0

    has_acceleration_limits: false
    max_acceleration: 5


  wrist_2_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: 1.0

    has_acceleration_limits: false
    max_acceleration: 5


  wrist_3_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28

    has_velocity_limits: true
    max_velocity: 1.0

    has_acceleration_limits: false
    max_acceleration: 5
